name: syntone
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - librosa
  - torchvision
  - pytorch
  - torchaudio
  - pytorch-cuda=11.8
  - pip=23.3.1
  - matplotlib
  - seaborn
  - ipykernel
  - celluloid
  - tqdm
  - pytorch-model-summary
  - pip:
    - audiomentations==0.34.1
    - click==8.1.7
    - future==0.18.3
    - imageio==2.33.0
    - pandas==2.1.3
    - pyitlib==0.2.3
    - scikit-learn==0.24.0
    - torch-summary==1.4.5